micronaut:
  application:
    name: micronaut_demo
datasource's:
  default:
    url: jdbc:mysql://localhost:3306/BlogDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: scott
    password: tiger
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
